// <auto-generated />
namespace Itc.Am.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201706060823233_WTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
